[tools]
opentofu = "{{.OpentofuVersion}}"
terragrunt = "{{.TerragruntVersion}}"

pre-commit = "4.2.0"
tflint = "0.58.0"
tfsec = "1.28.14"
trivy = "0.64.1"
checkov = "3.2.447"

[env]
PROJECT_NAME = "{{.ProjectName}}"
PROJECT_VERSION = "{{.ProjectVersion}}"

TG_PARALLELISM = "5"
